version: '3.8'

services:
  hayat-blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - hayat-blog-db:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/hayat-blog.sqlite
    restart: unless-stopped

volumes:
  hayat-blog-db:
    driver: local
